    const data = [{
        eventk: "0",
        pcgamer: "img/pcgamer.png",
        nampc: "Monster PC",
        precipc: "$1889",
        intelcore: "img/intelcore.png",
        corename: "Intel Core I9-12700F 12-Core",
        coreprice: "$339",
        nvidia2: "img/nvidia2.png",
        graficname: "NVIDIA geforce RTX 3070 8GB (VR READY)",
        graficprice: "$599",
        DDR4: "img/DDR4.png",
        DDR4name: "16GB DDR4 dual channel",
        DDR4price: "$79",
        SSD: "img/SSD.png",
        SSDname: "1TB NVME M.2",
        SSDprice: "$99",
        cool: "img/cool.png",
        coolname: "CM MasterLiquid ML240L",
        coolprice: "$99",
        fan: "img/fan.png",
        fanname: "QTY 4X CM MasterFans RGB",
        fanprice: "$49",
        gamercase: "img/pcgamer.",
        gamercasename: "Cooler Master TD5000 RGB",
        gamercaseprice: "$129",
        fuente: "img/fuente.png",
        fuentename: "700W ATX 80 Plus Gold",
        fuenteprice: "$89",
        motherb: "img/motherb.png",
        motherbname: "Asus B660 Series | Intel",
        motherbprice: "$149"
    },
    {
        eventk: "1",
        pcgamer: "img/pcgamer.png",
        nampc: "Cruiser Build",
        precipc: "$1759",
        intelcore: "img/intelcore.png",
        corename: "Intel Core I9-12700F 12-Core",
        coreprice: "$339",
        nvidia2: "img/nvidia2.png",
        graficname: "NVIDIA geforce RTX 3070 8GB (VR READY)",
        graficprice: "$599",
        DDR4: "img/DDR4.png",
        DDR4name: "16GB DDR4 dual channel",
        DDR4price: "$79",
        SSD: "img/SSD.png",
        SSDname: "1TB NVME M.2",
        SSDprice: "$99",
        cool: "img/cool.png",
        coolname: "CM MasterLiquid ML240L",
        coolprice: "$99",
        fan: "img/fan.png",
        fanname: "QTY 4X CM MasterFans RGB",
        fanprice: "$49",
        gamercase: "img/pcgamer.",
        gamercasename: "Cooler Master TD5000 RGB",
        gamercaseprice: "$129",
        fuente: "img/fuente.png",
        fuentename: "700W ATX 80 Plus Gold",
        fuenteprice: "$89",
        motherb: "img/motherb.png",
        motherbname: "Asus B660 Series | Intel",
        motherbprice: "$149"
    },
    {
        eventk: "2",
        pcgamer: "img/pcgamer.png",
        nampc: "Nasa PC",
        precipc: "$1679",
        intelcore: "img/intelcore.png",
        corename: "Intel Core I9-12700F 12-Core",
        coreprice: "$339",
        nvidia2: "img/nvidia2.png",
        graficname: "NVIDIA geforce RTX 3070 8GB (VR READY)",
        graficprice: "$599",
        DDR4: "img/DDR4.png",
        DDR4name: "16GB DDR4 dual channel",
        DDR4price: "$79",
        SSD: "img/SSD.png",
        SSDname: "1TB NVME M.2",
        SSDprice: "$99",
        cool: "img/cool.png",
        coolname: "CM MasterLiquid ML240L",
        coolprice: "$99",
        fan: "img/fan.png",
        fanname: "QTY 4X CM MasterFans RGB",
        fanprice: "$49",
        gamercase: "img/pcgamer.",
        gamercasename: "Cooler Master TD5000 RGB",
        gamercaseprice: "$129",
        fuente: "img/fuente.png",
        fuentename: "700W ATX 80 Plus Gold",
        fuenteprice: "$89",
        motherb: "img/motherb.png",
        motherbname: "Asus B660 Series | Intel",
        motherbprice: "$149"
    },
    {
        eventk: "3",
        pcgamer: "img/pcgamer.png",
        nampc: "Budget Build",
        precipc: "$1299",
        intelcore: "img/intelcore.png",
        corename: "Intel Core I9-12700F 12-Core",
        coreprice: "$339",
        nvidia2: "img/nvidia2.png",
        graficname: "NVIDIA geforce RTX 3070 8GB (VR READY)",
        graficprice: "$599",
        DDR4: "img/DDR4.png",
        DDR4name: "16GB DDR4 dual channel",
        DDR4price: "$79",
        SSD: "img/SSD.png",
        SSDname: "1TB NVME M.2",
        SSDprice: "$99",
        cool: "img/cool.png",
        coolname: "CM MasterLiquid ML240L",
        coolprice: "$99",
        fan: "img/fan.png",
        fanname: "QTY 4X CM MasterFans RGB",
        fanprice: "$49",
        gamercase: "img/pcgamer.",
        gamercasename: "Cooler Master TD5000 RGB",
        gamercaseprice: "$129",
        fuente: "img/fuente.png",
        fuentename: "700W ATX 80 Plus Gold",
        fuenteprice: "$89",
        motherb: "img/motherb.png",
        motherbname: "Asus B660 Series | Intel",
        motherbprice: "$149"
        }]
    export default data